Select * 
FROM BOOKS_DETAILS

Select * 
FROM CUSTOMER_BOOKS_RATINGS_DETAILS

With Main AS
(
Select c.*, TITLE, AUTHOR, YEAR, PUBLISHER
FROM CUSTOMER_BOOKS_RATINGS_DETAILS c
LEFT JOIN BOOKS_DETAILS bd
	ON c.ISBN = bd.ISBN
)
Select TITLE, AUTHOR, count(NULLIF(RATING,0)) AS NUM_ROWS, avg(CAST(NULLIF(RATING,0) AS INT)) AS AVERAGE_RATING, count(*) * avg(CAST(RATING AS INT)) AS TOTAL_RATING
FROM Main 
GROUP BY TITLE, AUTHOR
ORDER BY 5 DESC


Select distinct c.ISBN, d.ISBN, TITLE, LEN(c.ISBN) AS LEN_RATE_ISBN, LEN(d.ISBN) AS LEN_BOOK_ISBN
FROM CUSTOMER_BOOKS_RATINGS_DETAILS c
LEFT JOIN BOOKS_DETAILS d
	ON c.ISBN = d.ISBN
ORDER BY d.ISBN DESC

Select count(distinct a.ISBN)
FROM BOOKS_DETAILS a
JOIN CUSTOMER_BOOKS_RATINGS_DETAILS b
	ON a.ISBN = b.ISBN

Select *
FROM CUSTOMER_BOOKS_RATINGS_DETAILS

Select * 
FROM BOOKS_USERS

Select CUSTOMER_NBR, CITY, [STATE TERRITORY], COUNTRY, AGE, TITLE, AUTHOR, YEAR, PUBLISHER, RATING
FROM CUSTOMER_BOOKS_RATINGS_DETAILS a
JOIN BOOKS_USERS b
	ON b.[USER] = a.CUSTOMER_NBR
JOIN BOOKS_DETAILS c
	ON a.ISBN = c.ISBN
WHERE CUSTOMER_NBR NOT IN ('488/1','.0330486187;6')
ORDER BY TITLE
